name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2' # chỉnh version bạn dùng

      - name: Install dependencies
        working-directory: ./font_end
        run: flutter pub get

      # - name: Run tests
      #   working-directory: ./font_end
      #   run: flutter test

      - name: Build APK
        working-directory: ./font_end
        run: flutter build apk --debug

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: flutter-debug-apk
          path: font_end/build/app/outputs/flutter-apk/app-debug.apk
